const vcarServicesStyle = {
    section: {
        padding: "80px 0",
        background: "linear-gradient(135deg, #0f1b33 0%, #1a2744 40%, #243555 100%)",
        position: "relative" as const,
        overflow: "hidden",
        "&::before": {
            content: '""',
            position: "absolute",
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            background: "radial-gradient(ellipse at 80% 20%, rgba(255,255,255,0.03) 0%, transparent 60%)",
            pointerEvents: "none",
        },
    },
    container: {
        paddingRight: "15px",
        paddingLeft: "15px",
        marginRight: "auto",
        marginLeft: "auto",
        width: "100%",
        "@media (min-width: 576px)": { maxWidth: "540px" },
        "@media (min-width: 768px)": { maxWidth: "720px" },
        "@media (min-width: 992px)": { maxWidth: "960px" },
        "@media (min-width: 1200px)": { maxWidth: "1140px" },
    },
    headerArea: {
        textAlign: "center" as const,
        marginBottom: "60px",
    },
    logoContainer: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "15px",
        marginBottom: "12px",
    },
    logoImg: {
        width: "50px",
        height: "50px",
        objectFit: "contain" as const,
    },
    brandName: {
        fontFamily: '"Roboto Slab", "Times New Roman", serif',
        fontSize: "1.8rem",
        fontWeight: 700,
        color: "#ffffff",
        letterSpacing: "3px",
        textTransform: "uppercase" as const,
        margin: 0,
    },
    subtitle: {
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontSize: "0.85rem",
        fontWeight: 400,
        color: "rgba(255,255,255,0.5)",
        letterSpacing: "8px",
        textTransform: "uppercase" as const,
        marginTop: "5px",
    },
    divider: {
        width: "60px",
        height: "3px",
        background: "linear-gradient(90deg, #c8956c, #e8b88a)",
        margin: "20px auto 0",
        borderRadius: "2px",
    },
    cardsRow: {
        display: "flex",
        justifyContent: "center",
        gap: "30px",
        flexWrap: "wrap" as const,
        "@media (max-width: 768px)": {
            flexDirection: "column" as const,
            alignItems: "center",
        },
    },
    card: {
        background: "rgba(255,255,255,0.04)",
        backdropFilter: "blur(10px)",
        border: "1px solid rgba(255,255,255,0.08)",
        borderRadius: "16px",
        padding: "40px 30px",
        width: "280px",
        textAlign: "center" as const,
        transition: "all 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94)",
        position: "relative" as const,
        overflow: "hidden",
        "&:hover": {
            transform: "translateY(-8px)",
            background: "rgba(255,255,255,0.08)",
            border: "1px solid rgba(200,149,108,0.3)",
            boxShadow: "0 20px 40px rgba(0,0,0,0.3)",
        },
        "&::after": {
            content: '""',
            position: "absolute",
            top: 0,
            left: "50%",
            transform: "translateX(-50%)",
            width: "60%",
            height: "2px",
            background: "linear-gradient(90deg, transparent, rgba(200,149,108,0.6), transparent)",
            opacity: 0,
            transition: "opacity 0.4s ease",
        },
        "&:hover::after": {
            opacity: 1,
        },
    },
    cardIcon: {
        width: "60px",
        height: "60px",
        borderRadius: "50%",
        background: "linear-gradient(135deg, rgba(200,149,108,0.15), rgba(200,149,108,0.05))",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        margin: "0 auto 20px",
        border: "1px solid rgba(200,149,108,0.2)",
        "& svg": {
            fontSize: "28px",
            color: "#c8956c",
        },
    },
    cardTitle: {
        fontFamily: '"Roboto Slab", "Times New Roman", serif',
        fontSize: "1.15rem",
        fontWeight: 700,
        color: "#ffffff",
        marginBottom: "12px",
        letterSpacing: "0.5px",
    },
    cardDescription: {
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontSize: "0.9rem",
        fontWeight: 300,
        color: "rgba(255,255,255,0.6)",
        lineHeight: "1.7",
        margin: 0,
    },
    contactArea: {
        marginTop: "60px",
        textAlign: "center" as const,
    },
    contactButton: {
        display: "inline-block",
        padding: "14px 40px",
        background: "linear-gradient(135deg, #c8956c, #b07a52)",
        color: "#ffffff",
        fontFamily: '"Roboto Slab", "Times New Roman", serif',
        fontSize: "0.9rem",
        fontWeight: 600,
        letterSpacing: "2px",
        textTransform: "uppercase" as const,
        textDecoration: "none",
        borderRadius: "50px",
        border: "none",
        cursor: "pointer",
        transition: "all 0.3s ease",
        boxShadow: "0 4px 15px rgba(200,149,108,0.3)",
        "&:hover": {
            transform: "translateY(-2px)",
            boxShadow: "0 8px 25px rgba(200,149,108,0.4)",
            background: "linear-gradient(135deg, #d4a57c, #c8956c)",
        },
    },
    contactInfo: {
        display: "flex",
        justifyContent: "center",
        gap: "40px",
        marginTop: "25px",
        flexWrap: "wrap" as const,
    },
    contactItem: {
        display: "flex",
        alignItems: "center",
        gap: "10px",
        color: "rgba(255,255,255,0.6)",
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
        fontSize: "0.95rem",
        fontWeight: 300,
        "& svg": {
            fontSize: "20px",
            color: "#c8956c",
        },
    },
};

export default vcarServicesStyle;
